# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportName', models.CharField(max_length=100, verbose_name='反映人姓名')),
                ('adress', models.CharField(max_length=200, verbose_name='反映人住址')),
                ('question', models.TextField(verbose_name='反映的问题')),
                ('belongUnit', models.CharField(max_length=200, verbose_name='责任单位')),
                ('remark', models.TextField(verbose_name='备注')),
                ('creatTime', models.DateTimeField(verbose_name='创建时间')),
                ('finishTime', models.DateTimeField(blank=True, verbose_name='化解完成时间')),
                ('belongArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xinfang.Area', verbose_name='所属区域的id')),
            ],
        ),
        migrations.CreateModel(
            name='CaseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=100, verbose_name='化解状态')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.CharField(max_length=10000, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='belongUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xinfang.User', verbose_name='县包案领导'),
        ),
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xinfang.CaseState', verbose_name='目前化解的情况'),
        ),
    ]
