# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xinfang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2017, 5, 18, 9, 16, 15, 74570, tzinfo=utc), max_length=50, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=datetime.datetime(2017, 5, 18, 9, 16, 18, 402667, tzinfo=utc), max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
